# Paths
result_folder_path: './results/mode_4'
SNP_csv_path: './data/Toy_X_snps.csv'
breed_list_text_path: './data/Toy_a_short_breed_list.txt'
label_path: './data/Toy_Y_labels.csv'

# Training Params
pca_components: 0.95
random_state: 42
test_size: 0.3
